name: Build

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: install deps
      run: sudo apt install vice cc65

    - name: build CCGMS
      run: |
        make -j$(nproc) EXOMIZER=1
        cp build/disk.d64 ccgms.d64

    - name: build CCGMS (EASYFLASH version)
      run: |
        make -j$(nproc) EASYFLASH=1 EXOMIZER=1
        cp build/disk.d64 ccgms-exo.d64

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          *.d64

    - name: Create release                                                      
      if: startsWith(github.ref, 'refs/tags/')                                  
      uses: softprops/action-gh-release@v1                                      
      with:                                                                     
        files: |
          *.d64
        fail_on_unmatched_files: true
        body: "Automatically created release"                                                                            
