name: Build

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: install deps
      run: sudo apt install vice cc65

    - name: build CCGMS
      run: |
        make -j$(nproc)
        c1541 -format ccgms,fu d64 ccgms.d64 -write build/ccgmsterm.prg
        make clean

    - name: build CCGMS (EASYFLASH version)
      run: |
        make -j$(nproc) EASYFLASH=1
        c1541 -format ccgms-easyflash,fu d64 ccgms-easyflash.d64 -write build/ccgmsterm.prg
        make clean

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          *.d64

    - name: Create release                                                      
      if: startsWith(github.ref, 'refs/tags/')                                  
      uses: softprops/action-gh-release@v1                                      
      with:                                                                     
        files: |
          *.d64
        fail_on_unmatched_files: true
        body: "Automatically created release"                                                                            
